# application configuration for the Spring Boot app
  # dependencies:
    # 1. Java application development tooling
  # hightlights:
    # 1. make sure server.http2.enabled is set to true
    # 2. to enable verbose logging, please enable logging for org.apache objects as described below.
    # 3. this file should be put in "src/main/resources/application.yaml" of the application code base or other place that can be read by the appliation in the runtime. You may also omit some sections that are not applicable.
    # 4. the logging.config may need to be changed according to your actual situation

api:
  main-event-name: api-v1-$${api.domain}-$${api.app-name}

encryption:
  status: false

debug: false

logging:
  level:
    root: INFO
    org:
      apache:
        tomcat: TRACE
        catalina: TRACE
  # change this line accordingly when needed
  config: classpath:logback-spring.xml

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - purgecache
          - prometheus
  health:
    livenessstate:
      enabled: true
    r2dbc:
      enabled: true
    readinessstate:
      enabled: true
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

probe:
  liveness:
    initialDelaySeconds: 120
  readiness:
    initialDelaySeconds: 120

spring:
  devtools:
    add-properties: true
  jmx:
    enabled: true
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      indent-output: true

server:
  max-http-header-size: 40KB
  compression:
    enabled: true
    min-response-size: 512
  http2:
    enabled: true
  port: 8080
  tomcat:
    redirect-context-root: false

trace: false
